"""rename column ticker in name

Revision ID: 91a8762449b5
Revises: d93f63721c1f
Create Date: 2026-02-01 17:15:39.364058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a8762449b5'
down_revision: Union[str, Sequence[str], None] = 'd93f63721c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('prices', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('prices', 'name')
    # ### end Alembic commands ###
